### ISSUE TITLE
Semantic Scholar -> Open Alex

### ISSUE THREAD

**Issue by SbstnErhrdt** [max-planck-innovation-competition/go-semanticscholar#1]
https://github.com/max-planck-innovation-competition/go-semanticscholar/blob/f75cfa13cbb332dcd91d53ff2839fcba606deee1/pkg/semanticscholar/publication.go#L3C6-L3C17

**Comment by Michael-E-Rose** [comment]
Seems done as active development in https://github.com/max-planck-innovation-competition/go-openalex is taking place.
